config/routes.rb
MenuHistory::Application.routes.draw do

  root to: "home#index"
  resources :home

  get '/locu/:name' => 'foods#local_menu_search', as: :locu
  get '/yelp/:name' => 'foods#yelp', as: :yelp
  get '/foods/:decade' => 'foods#index', as: :foods

  get '/decade_data' => 'foods#json_output'

end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  def json_output
    min_max_array = params[:decade].split(',')
    @min = min_max_array[0]
    @max = min_max_array[1]
    @decade_popular = HTTParty.get("http://api.menus.nypl.org/dishes?token=selsce5qphehgzeqw2cke6jb2e&min_year=#{@min}&max_year=#{@max}&sort_by=popularity")
    output = []


    @decade_popular["dishes"][0..9].each do |dish|
      img_name = dish["name"].gsub(/[^\w]/, "");

      output << {
          startDate: ["1850","#{dish["first_appeared"]}"].max,
          endDate: ["2012","#{dish["last_appeared"]}"].min,
          headline: dish["name"],
          asset: {media: "http://#{img_name}.jpg.to"}
      }
    end

    json_obj = {
      timeline: {
      headline:"Dish on Dishes",
      type:"default",
      text:"Brought to you by NYPL",
      startDate: "#{@min}",
      date: output
      }
    };

    respond_to do |format|
      format.json { render json:json_obj }
    end

  end

  # GET /foods
  # GET /foods.json
  def index
    min_max_array = params[:decade].split(',')
    @min = min_max_array[0]
    @max = min_max_array[1]
    @decade_popular = HTTParty.get("http://api.menus.nypl.org/dishes?token=selsce5qphehgzeqw2cke6jb2e&min_year=#{@min}&max_year=#{@max}&sort_by=popularity")
    @decade_obscure = HTTParty.get("http://api.menus.nypl.org/dishes?token=selsce5qphehgzeqw2cke6jb2e&min_year=#{@min}&max_year=#{@max}&sort_by=obscurity")
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  def local_menu_search
    @name = params[:name].split(' ').join('+')
    @local_search = HTTParty.get("http://api.locu.com/v1_0/menu_item/search/?api_key=6aa048a34d1b96643052e2b69318afddb0b53b21&name=#{@name}&radius=1000")
    if @local_search.length > 50
      @local_search = @local_search[0..49]
    end
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render action: 'show', status: :created, location: @food }
      else
        format.html { render action: 'new' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:dish, :year, :qty)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dish %><br>
    <%= f.text_field :dish %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.number_field :qty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<% @decade_popular["dishes"][0..9].each do |dish|  %>
  <div class="boxed">
    <h1><%= dish["name"] %></h1>
    <img src="http://<%= dish["name"] %>.jpg.to" alt="food image" height="42" width="42">
    <h4>On <%= dish["menus_appeared"]%> menus</h4>
    <h4>First appeared in <%= dish["first_appeared"] %></h4>
    <h4>Last appeared in <%= dish["last_appeared"] %></h4>
    <form method="link" action=<%= locu_path(dish["name"]) %>>
      <input class="finder" type="submit" value="Find Dish Today!">
    </form>
  </div>



<% end %>

<div id="timeline-embed">

</div>

<script>
  $(document).ready(function() {

      createStoryJS({
          type:       'timeline',
          width:      '100%',
          height:     '300px',
          source:      "/decade_data.json?decade=<%=@min%>,<%=@max%>",
          embed_id:   'timeline-embed'
      });
  });
</script>

app/views/foods/local_menu_search.html.erb
<h1><%= @local_lat %></h1>
<h1><%= @local_lon %></h1>


<style type="text/css">
  html { height: 100% }
  body {
    height: 100%;
    margin: 0;
    padding: 0;
    background-image: none;
  }

  #map-canvas {
    border-style:solid;
    border-width:1px;
    height: 800px; width: 1200px;
    margin: 50px auto;
  }

</style>


<div id="map-canvas" style="padding-left: 50px"/></div>


<script>


           //google maps API
function initialize() {


   // // first remove all markers if there are any

   //      deleteOverlays();

  // initialize new google maps LatLng object
  var myLatlng = new google.maps.LatLng(<%= @local_search['objects'][0]['venue']['lat'] %>, <%= @local_search['objects'][0]['venue']['long'] %>);

  // set the map options hash
  var mapOptions = {
    center: myLatlng,
    zoom: 3,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };

  var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);




  <% @local_search['objects'].each do |obj| %>

    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(<%=obj['venue']['lat']%>, <%=obj['venue']['long']%>),
      title: "<%=obj['venue']['name'].strip%>"
    });
    marker.setMap(map);

  <% end %>


}



google.maps.event.addDomListener(window, 'load', initialize);


</script>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MenuHistory</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<br><h1 style='text-align:center' id="title">Eating Through History</h1><br>

<!-- <div class='btn-group-vertical span2' id='buttons'> -->
  <a href=<%= foods_path('1851,1859') %> class="btn btn-primary btn-lg active" role="button">1850s</a>
  <a href=<%= foods_path('1860,1869') %> class="btn btn-primary btn-lg active" role="button">1860s</a>
  <a href=<%= foods_path('1870,1879') %> class="btn btn-primary btn-lg active" role="button">1870s</a>
  <a href=<%= foods_path('1880,1889') %> class="btn btn-primary btn-lg active" role="button">1880s</a>
  <a href=<%= foods_path('1890,1899') %> class="btn btn-primary btn-lg active" role="button">1890s</a>
  <a href=<%= foods_path('1900,1909') %> class="btn btn-primary btn-lg active" role="button">1900s</a>
  <a href=<%= foods_path('1910,1919') %> class="btn btn-primary btn-lg active" role="button">1910s</a>
  <a href=<%= foods_path('1920,1929') %> class="btn btn-primary btn-lg active" role="button">1920s</a>
  <a href=<%= foods_path('1930,1939') %> class="btn btn-primary btn-lg active" role="button">1930s</a>
  <a href=<%= foods_path('1940,1949') %> class="btn btn-primary btn-lg active" role="button">1940s</a>
  <a href=<%= foods_path('1950,1959') %> class="btn btn-primary btn-lg active" role="button">1950s</a>
  <a href=<%= foods_path('1960,1969') %> class="btn btn-primary btn-lg active" role="button">1960s</a>
  <a href=<%= foods_path('1970,1979') %> class="btn btn-primary btn-lg active" role="button">1970s</a>
  <a href=<%= foods_path('1980,1989') %> class="btn btn-primary btn-lg active" role="button">1980s</a>
  <a href=<%= foods_path('1990,1999') %> class="btn btn-primary btn-lg active" role="button">1990s</a>
  <a href=<%= foods_path('2000,2009') %> class="btn btn-primary btn-lg active" role="button">2000s</a>
  <a href=<%= foods_path('2010,2013') %> class="btn btn-primary btn-lg active" role="button">2010s</a>
<!-- </div> -->
<div>
  <ul id='menu-items' class='span7'></ul>
</div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC2ck8yFy7yYRff1B0DTQAM9Cpu_ao8lSA&sensor=true">
    </script>

    <title><%= content_for?(:title) ? yield(:title) : "MenuHistory" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

            <%= yield %>

  </body>
</html>